services:
  beermapping:
    image: aaropaltemaa/beermapping:latest
    container_name: beermapping
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8080:8080"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable # only watch containers with the label
